name: apos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  http:
  meta: ^1.1.6
  equatable: ^1.1.1
  rxdart: ^0.24.0

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.2
  date_range_picker: ^1.0.3
  intl: ^0.15.7
  syncfusion_flutter_charts: ^18.1.59
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.4.0
  bloc_test: ^5.1.0
  modal_progress_hud: ^0.1.3

flutter:

  uses-material-design: true

  assets:
   - images/splash.png
   - images/splash-1.png
   - images/validasi.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd-Bold
      fonts:
        - asset: fonts/CircularStd-Bold.ttf

    - family: CircularStd-Book
      fonts:
        - asset: fonts/Circular-Std-Book.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
